name: Publish

on:
  push:
    branches: master
  workflow_run:
    workflows: [ "Check PR" ]
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # allow GITHUB_TOKEN to publish packages
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm ci
      - name: Set git vars
        run: |
          git config --global user.name 'autopublish'
          git config --global user.email 'example@example.com'
      - run: npm version minor
      - name: Commit report
        run: |
          git push
#      - uses: JS-DevTools/npm-publish@v3
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          registry: "https://npm.pkg.github.com"
