on:
  push:
    branches: master

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # allow GITHUB_TOKEN to publish packages
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm ci
      - run: npm version minor
      - name: Commit report
        run: |
         git config --global user.name 'Your Name'
         git config --global user.email 'your-username@users.noreply.github.com'
         git push
#      - uses: JS-DevTools/npm-publish@v3
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          registry: "https://npm.pkg.github.com"
